=== Carlosherzab/Hito-individual-2Evaluacion_Carlos_Hernandez/hito individual 2 evaluacion_Carlos_Hernandez/pedidos.dtd
<!ELEMENT años (año)>
<!ELEMENT año (trimestre+)>
<!ATTLIST año anio CDATA #REQUIRED>
<!ELEMENT trimestre (pedidos)>
<!ATTLIST trimestre trim CDATA #REQUIRED>
<!ELEMENT Pedidos (pedido)>
<!ELEMENT pedido (nombre, apellidos, teléfono, dirección, correo_electrónico, fecha_inclusión, detalle_pedido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT teléfono (#PCDATA)>
<!ELEMENT dirección (calle, ciudad, código_postal, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT código_postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT correo_electrónico (#PCDATA)>
<!ELEMENT fecha_inclusión (#PCDATA)>
<!ELEMENT detalle_pedido (número_pedido, fecha_compra, fecha_entrega, total_factura, producto)>
<!ELEMENT número_pedido (#PCDATA)>
<!ELEMENT fecha_compra (#PCDATA)>
<!ELEMENT fecha_entrega (#PCDATA)>
<!ELEMENT total_factura (#PCDATA)>
<!ELEMENT producto (nombre_producto, referencia, precio, unidades)>
<!ELEMENT nombre_producto (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>

=== Carlosherzab/Hito-individual-2Evaluacion_Carlos_Hernandez/hito individual 2 evaluacion_Carlos_Hernandez/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE años SYSTEM "pedidos.dtd">
<años> 
<año anio="2021">
    <trimestre trim="1">
      <Pedidos>
        <pedido>
          <nombre>Iván</nombre>
          <apellidos>Moreno</apellidos>
          <teléfono>621456789</teléfono>
          <dirección>
            <calle>Serrano</calle>
            <ciudad>Madrid</ciudad>
            <código_postal>28976</código_postal>
            <provincia>Madrid</provincia>
          </dirección>
          <correo_electrónico>ivánmoreno@gmail.com</correo_electrónico>
          <fecha_inclusión>2021-01-02</fecha_inclusión>
          <detalle_pedido>
            <número_pedido>1</número_pedido>
            <fecha_compra>2021-01-02</fecha_compra>
            <fecha_entrega>2021-01-03</fecha_entrega>
            <total_factura>70 €</total_factura>
            <producto>
              <nombre_producto>Mando Play 4</nombre_producto>
              <referencia>P0001</referencia>
              <precio>35 €</precio>
              <unidades>2</unidades>
            </producto>
          </detalle_pedido>
        </pedido>
    <pedido>
      <nombre>Alba</nombre>
      <apellidos>Grisaleña</apellidos>
      <teléfono>678902012</teléfono>
      <dirección>
        <calle>Lionel Messi</calle>
        <ciudad>Madrid</ciudad>
        <código_postal>28021</código_postal>
        <provincia>Madrid</provincia>
      </dirección>
      <correo_electrónico>albagrs@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-05</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>2</número_pedido>
        <fecha_compra>2021-01-06</fecha_compra>
        <fecha_entrega>2021-01-09</fecha_entrega>
        <total_factura>300 €</total_factura>
        <producto>
          <nombre_producto>Nintendo switch oled</nombre_producto>
          <referencia>P0002</referencia>
          <precio>300 €</precio>
          <unidades>1</unidades>
        </producto>
      </detalle_pedido>
    </pedido>
    <pedido>
      <nombre>Carlos</nombre>
      <apellidos>Hernández</apellidos>
      <teléfono>678902345</teléfono>
      <dirección>
        <calle>Legazpi</calle>
        <ciudad>Madrid</ciudad>
        <código_postal>28021</código_postal>
        <provincia>Madrid</provincia>
      </dirección>
      <correo_electrónico>cxrlos@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-06</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>3</número_pedido>
        <fecha_compra>2021-01-06</fecha_compra>
        <fecha_entrega>2021-01-08</fecha_entrega>
        <total_factura>20 €</total_factura>
        <producto>
          <nombre_producto>Gta V PS5</nombre_producto>
          <referencia>P0003</referencia>
          <precio>20 €</precio>
          <unidades>1</unidades>
        </producto>
      </detalle_pedido>
    </pedido>
    <pedido>
      <nombre>Alejandro</nombre>
      <apellidos>Ponce</apellidos>
      <teléfono>698090856</teléfono>
      <dirección>
        <calle>Juan Ramón Jiménez</calle>
        <ciudad>Murcia</ciudad>
        <código_postal>30001</código_postal>
        <provincia>Murcia</provincia>
      </dirección>
      <correo_electrónico>ponce@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-10</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>4</número_pedido>
        <fecha_compra>2021-02-12</fecha_compra>
        <fecha_entrega>2021-02-13</fecha_entrega>
        <total_factura>120 €</total_factura>
        <producto>
          <nombre_producto>God Of War Ragnarok PS5</nombre_producto>
          <referencia>P0004</referencia>
          <precio>60 €</precio>
          <unidades>2</unidades>
        </producto>
      </detalle_pedido>
    </pedido>
    <pedido>
      <nombre>María</nombre>
      <apellidos>Zabalgo</apellidos>
      <teléfono>679654321</teléfono>
      <dirección>
        <calle>Greco</calle>
        <ciudad>Sevilla</ciudad>
        <código_postal>29890</código_postal>
        <provincia>Sevilla</provincia>
      </dirección>
      <correo_electrónico>maría@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-15</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>5</número_pedido>
        <fecha_compra>2021-02-16</fecha_compra>
        <fecha_entrega>2021-02-18</fecha_entrega>
        <total_factura>270 €</total_factura>
        <producto>
          <nombre_producto>Play 4 Pro</nombre_producto>
          <referencia>P0005</referencia>
          <precio>270 €</precio>
          <unidades>1</unidades>
        </producto>
      </detalle_pedido>
    </pedido>
    <pedido>
      <nombre>Carlos</nombre>
      <apellidos>Hernández</apellidos>
      <teléfono>678902345</teléfono>
      <dirección>
        <calle>Legazpi</calle>
        <ciudad>Madrid</ciudad>
        <código_postal>28021</código_postal>
        <provincia>Madrid</provincia>
      </dirección>
      <correo_electrónico>cxrlos@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-06</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>6</número_pedido>
        <fecha_compra>2021-02-20</fecha_compra>
        <fecha_entrega>2021-02-21</fecha_entrega>
        <total_factura>24 €</total_factura>
        <producto>
          <nombre_producto>Cuphead Nintendo Switch</nombre_producto>
          <referencia>P0006</referencia>
          <precio>24 €</precio>
          <unidades>1</unidades>
        </producto>
      </detalle_pedido>
    </pedido>
    <pedido>
      <nombre>Carlos</nombre>
      <apellidos>Hernández</apellidos>
      <teléfono>678902345</teléfono>
      <dirección>
        <calle>Legazpi</calle>
        <ciudad>Madrid</ciudad>
        <código_postal>28021</código_postal>
        <provincia>Madrid</provincia>
      </dirección>
      <correo_electrónico>cxrlos@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-06</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>7</número_pedido>
        <fecha_compra>2021-03-23</fecha_compra>
        <fecha_entrega>2021-03-25</fecha_entrega>
        <total_factura>7 €</total_factura>
        <producto>
          <nombre_producto>Call of Duty Black Ops 4</nombre_producto>
          <referencia>P0007</referencia>
          <precio>7 €</precio>
          <unidades>1</unidades>
        </producto>
      </detalle_pedido>
    </pedido>
    <pedido>
      <nombre>Alba</nombre>
      <apellidos>Grisaleña</apellidos>
      <teléfono>678902012</teléfono>
      <dirección>
        <calle>Lionel Messi</calle>
        <ciudad>Madrid</ciudad>
        <código_postal>28021</código_postal>
        <provincia>Madrid</provincia>
      </dirección>
      <correo_electrónico>albagrs@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-05</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>8</número_pedido>
        <fecha_compra>2021-03-24</fecha_compra>
        <fecha_entrega>2021-03-25</fecha_entrega>
        <total_factura>25 €</total_factura>
        <producto>
          <nombre_producto>Cuphead switch</nombre_producto>
          <referencia>P0008</referencia>
          <precio>25 €</precio>
          <unidades>1</unidades>
        </producto>
      </detalle_pedido>
    </pedido>
    <pedido>
      <nombre>Daniel</nombre>
      <apellidos>Moreno</apellidos>
      <teléfono>678932121</teléfono>
      <dirección>
        <calle>Títeres</calle>
        <ciudad>Galicia</ciudad>
        <código_postal>22121</código_postal>
        <provincia>Galicia</provincia>
      </dirección>
      <correo_electrónico>moreno@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-19</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>9</número_pedido>
        <fecha_compra>2021-03-24</fecha_compra>
        <fecha_entrega>2021-03-25</fecha_entrega>
        <total_factura>15 €</total_factura>
        <producto>
          <nombre_producto>The Last Of Us parte I PS4</nombre_producto>
          <referencia>P0009</referencia>
          <precio>15 €</precio>
          <unidades>1</unidades>
        </producto>
      </detalle_pedido>
    </pedido>
    <pedido>
      <nombre>Carlos</nombre>
      <apellidos>Hernández</apellidos>
      <teléfono>678902345</teléfono>
      <dirección>
        <calle>Legazpi</calle>
        <ciudad>Madrid</ciudad>
        <código_postal>28021</código_postal>
        <provincia>Madrid</provincia>
      </dirección>
      <correo_electrónico>cxrlos@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-06</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>10</número_pedido>
        <fecha_compra>2021-03-28</fecha_compra>
        <fecha_entrega>2021-03-30</fecha_entrega>
        <total_factura>10 €</total_factura>
        <producto>
          <nombre_producto>God Of War PS4</nombre_producto>
          <referencia>P0010</referencia>
          <precio>10 €</precio>
          <unidades>1</unidades>
        </producto>
      </detalle_pedido>
    </pedido>
</Pedidos>
</trimestre>
    <trimestre trim="2">
      <Pedidos>
        <pedido>
          <nombre>Ernesto</nombre>
      <apellidos>Sevilla</apellidos>
      <teléfono>677754770</teléfono>
      <dirección>
        <calle>Paulatib</calle>
        <ciudad>Galicia</ciudad>
        <código_postal>20021</código_postal>
        <provincia>Galicia</provincia>
      </dirección>
      <correo_electrónico>sevilla@gmail.com</correo_electrónico>
      <fecha_inclusión>2021-01-26</fecha_inclusión>
      <detalle_pedido>
        <número_pedido>11</número_pedido>
        <fecha_compra>2021-04-22</fecha_compra>
        <fecha_entrega>2021-04-24</fecha_entrega>
        <total_factura>120 €</total_factura>
        <producto>
